src/Dsg/agenciaBundle/Entity/Trabajos.php
<?php

namespace Dsg\agenciaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Dsg\agenciaBundle\Funciones\Amigable;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Trabajos
 */
class Trabajos
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $tipo;

    /**
     * @var string
     */
    private $compania;

    /**
     * @var string
     */
    private $logo;

    /**
     * @var string
     */
    private $url;

    /**
     * @var string
     */
    private $posicion;

    /**
     * @var string
     */
    private $localidad;

    /**
     * @var string
     */
    private $descripcion;

    /**
     * @var string
     */
    private $how_to_apply;

    /**
     * @var string
     */
    private $token;

    /**
     * @var boolean
     */
    private $publico;

    /**
     * @var boolean
     */
    private $activado;

    /**
     * @var string
     */
    private $email;

    /**
     * @var \DateTime
     */
    private $finaliza;

    /**
     * @var \DateTime
     */
    private $creado;

    /**
     * @var \DateTime
     */
    private $actualizado;

    /**
     * @var \Dsg\agenciaBundle\Entity\Categoria
     */
    private $categoria;
    
    public $file;
    
    
    /**
     * [__construct description]
     */
    public function __construct()
    {
        $this->creado = new \DateTime();
        $this->actualizado =new \DateTime();
    }

    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set tipo
     *
     * @param string $tipo
     * @return Trabajos
     */
    public function setTipo($tipo)
    {
        $this->tipo = $tipo;

        return $this;
    }

    /**
     * Get tipo
     *
     * @return string 
     */
    public function getTipo()
    {
        return $this->tipo;
    }
    
    

    /**
     * Set compania
     *
     * @param string $compania
     * @return Trabajos
     */
    public function setCompania($compania)
    {
        $this->compania = $compania;

        return $this;
    }

    /**
     * Get compania
     *
     * @return string 
     */
    public function getCompania()
    {
        return $this->compania;
    }

    /**
     * Set logo
     *
     * @param string $logo
     * @return Trabajos
     */
    public function setLogo($logo)
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * Get logo
     *
     * @return string 
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Trabajos
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set posicion
     *
     * @param string $posicion
     * @return Trabajos
     */
    public function setPosicion($posicion)
    {
        $this->posicion = $posicion;

        return $this;
    }

    /**
     * Get posicion
     *
     * @return string 
     */
    public function getPosicion()
    {
        return $this->posicion;
    }

    /**
     * Set localidad
     *
     * @param string $localidad
     * @return Trabajos
     */
    public function setLocalidad($localidad)
    {
        $this->localidad = $localidad;

        return $this;
    }

    /**
     * Get localidad
     *
     * @return string 
     */
    public function getLocalidad()
    {
        return $this->localidad;
    }

    /**
     * Set descripcion
     *
     * @param string $descripcion
     * @return Trabajos
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get descripcion
     *
     * @return string 
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * Set how_to_apply
     *
     * @param string $howToApply
     * @return Trabajos
     */
    public function setHowToApply($howToApply)
    {
        $this->how_to_apply = $howToApply;

        return $this;
    }

    /**
     * Get how_to_apply
     *
     * @return string 
     */
    public function getHowToApply()
    {
        return $this->how_to_apply;
    }

    /**
     * Set token
     *
     * @param string $token
     * @return Trabajos
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * Get token
     *
     * @return string 
     */
    public function getToken()
    {
        return $this->token;
    }
    
    public function setTokenValue()
    {
        if(!$this->getToken()) {
            $this->token = sha1($this->getEmail().rand(11111, 99999));
        }
    }
    
    /**
     * Set publico
     *
     * @param boolean $publico
     * @return Trabajos
     */
    public function setPublico($publico)
    {
        $this->publico = $publico;

        return $this;
    }

    /**
     * Get publico
     *
     * @return boolean 
     */
    public function getPublico()
    {
        return $this->publico;
    }

    /**
     * Set activado
     *
     * @param boolean $activado
     * @return Trabajos
     */
    public function setActivado($activado)
    {
        $this->activado = $activado;

        return $this;
    }

    /**
     * Get activado
     *
     * @return boolean 
     */
    public function getActivado()
    {
        return $this->activado;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Trabajos
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set finaliza
     *
     * @param \DateTime $finaliza
     * @return Trabajos
     */
    public function setFinaliza($finaliza)
    {
        $this->finaliza = $finaliza;

        return $this;
    }

    /**
     * Get finaliza
     *
     * @return \DateTime 
     */
    public function getFinaliza()
    {
        return $this->finaliza;
    }

    /**
     * Set creado
     *
     * @param \DateTime $creado
     * @return Trabajos
     */
    public function setCreado($creado)
    {
        $this->creado = $creado;

        return $this;
    }

    /**
     * Get creado
     *
     * @return \DateTime 
     */
    public function getCreado()
    {
        return $this->creado;
    }

    /**
     * Set actualizado
     *
     * @param \DateTime $actualizado
     * @return Trabajos
     */
    public function setActualizado($actualizado)
    {
        $this->actualizado = $actualizado;

        return $this;
    }

    /**
     * Get actualizado
     *
     * @return \DateTime 
     */
    public function getActualizado()
    {
        return $this->actualizado;
    }

    /**
     * Set categoria
     *
     * @param \Dsg\agenciaBundle\Entity\Categoria $categoria
     * @return Trabajos
     */
    public function setCategoria(\Dsg\agenciaBundle\Entity\Categoria $categoria = null)
    {
        $this->categoria = $categoria;

        return $this;
    }
    
    
        // Añadimos estos métodos para hacer url amigables
    public function getCompaniaSlug()
    {
        return Amigable::urlAmigable($this->getCompania()); ;
    }

    public function getPosicionSlug()
    {
        return Amigable::urlAmigable($this->getPosicion());
    }

    public function getLocalidadSlug()
    {
        return Amigable::urlAmigable($this->getLocalidad());
    }
    
    
    
    /**
     * Get categoria
     *
     * @return \Dsg\agenciaBundle\Entity\Categoria 
     */
    public function getCategoria()
    {
        return $this->categoria;
    }
    /**
     * @ORM\PrePersist
     */
    public function setCreadoValue()
    {
        if(!$this->getCreado())
        {
            $this->creado = new \DateTime();
        }
    }
    
    
    public function __toString() {
        return sprintf('%s at %s at %s (%s)', $this->getCategoria(), $this->getPosicion(), $this->getCompania(), $this->getLocalidad());
    }

    /**
     * @ORM\PrePersist
     */
    public function setFinalizaValue()
    {
        if(!$this->getFinaliza()) {
            $now = $this->getCreado() ? $this->getCreado()->format('U') : time();
            $this->finaliza = new \DateTime(date('Y-m-d H:i:s', $now + 86400 * 30));
        }
    }

    /**
     * @ORM\PreUpdate
     */
    public function setActualizadoValue()
    {
        $this->actualizado = new \DateTime();
    }
    
    public static function getTipos()
    {
        return array('Tiempo completo' => 'Tiempo Completo', 'Media jornada' => 'Media Jornada', 'Autonomo' => 'Autonomo');
    }
     
    public static function getTipoValues()
    {
        return array_keys(self::getTipos());
    }
    
    
    //Subir imagenes
     protected function getUploadDir()
    {
        return 'public/upload';
    }
 
 
    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }
 
 
    public function getWebPath()
    {
        return null === $this->logo ? null : $this->getUploadDir().'/'.$this->logo;
    }
 
 
    public function getAbsolutePath()
    {
        return null === $this->logo ? null : $this->getUploadRootDir().'/'.$this->logo;
    }    
    
    
    
    /**
     * @ORM\PrePersist
     */
    public function preUpload()
    {
        if (null !== $this->file) {
            
            if ($logo = $this->getAbsolutePath()) {
                unlink($logo);
            }
             
             $this->logo = uniqid().'.'.$this->file->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist
     */
    public function upload()
    {

src/Dsg/agenciaBundle/Form/TrabajosType.php
<?php

namespace Dsg\agenciaBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

use Dsg\agenciaBundle\Entity\Trabajos;

class TrabajosType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tipo', 'choice', array('choices' => Trabajos::getTipos(), 'choices_as_values' => true,))
            ->add('categoria', null,  array('placeholder'=> 'Selecciona una categoría'))
            ->add('compania')
            ->add('url')
            ->add('posicion')
            ->add('localidad')
            ->add('descripcion')
            ->add('how_to_apply', null, array('label' => '¿Como suscribirse?'))
            ->add('publico', null, array('label' => '¿Es publica?'))
            ->add('email')
            ->add('file', 'file', array('label' => 'Logotipo empresa', 'required' => false))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Dsg\agenciaBundle\Entity\Trabajos'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'formularioTrabajos';
    }
}

src/Dsg/agenciaBundle/Resources/views/Trabajos/admin.html.twig
<div id="job_actions">
    <h3>Administrar</h3>
    <div class="form-group">
        
        {% if not trabajos.activado %}
        
            <button class="btn btn-primary" type="button" onclick="location.href='{{ path('trabajos_edit', { 'token': trabajos.token }) }}'">Editar</button>
            <form action={{ path('trabajos_publish', { 'token': trabajos.token }) }} method="post">
                {{ form_widget(publish_form) }}
                <button type="submit">Publicar</button>
            </form>
            
        {% endif %}
        <form class="form-horizontal" action={{ path('trabajos_delete', { 'token': trabajos.token }) }} method="post">
            {{ form_widget(delete_form) }}
            <button class="btn btn-primary" type="submit" onclick="if(!confirm('Are you sure?')) { return false; }">Borrar</button>
        </form>
        {% if trabajos.activado %}
            <p{% if trabajos.finalizanPronto %} class="expires_soon" {% endif %}>
                {% if trabajos.finalizadoYa %}
                    Finalizado
                {% else %}
                    Finaliza en <strong>{{ trabajos.getDaysBeforeFinaliza }}</strong> días
                {% endif %}
 
                {% if trabajos.finalizanPronto %}
                    <form action={{ path('trabajos_extend', { 'token': trabajos.token }) }} method="post">
                        {{ form_widget(extend_form) }}
                        - <button type="submit">Ampliar</button> por 30 días más.
                    </form>
                {% endif %}
            </p>
        {% else %}
                [Pincha sobre el siguiente <a href={{ url('trabajos_preview', {'token': trabajos.token, 'compania': trabajos.companiaSlug, 'localidad': trabajos.localidadSlug, 'posicion': trabajos.posicionSlug }) }}>Link</a> para poder gestionar esta oferta en el futuro.]
        {% endif %}
    </div>
</div>

src/Dsg/agenciaBundle/Resources/views/Trabajos/buscar.html.twig
{% extends 'DsgagenciaBundle::layout.html.twig' %}

{% block content %}
    <div id="trabajos">
        {% include 'DsgagenciaBundle:Trabajos:listar.html.twig' with {'trabajos': trabajos} %}
    </div>
{% endblock %}

src/Dsg/agenciaBundle/Resources/views/Trabajos/edit.html.twig
{% extends 'DsgagenciaBundle::layout.html.twig' %}

{% form_theme edit_form _self %}

{% block form_errors %}
{% spaceless %}
    {% if errors|length > 0 %}
        <ul class="error_list">
            {% for error in errors %}
                <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endspaceless %}
{% endblock form_errors %}


{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('public/csspaginas/show.css') }}" type="text/css" media="all" />
{% endblock %}

{% block formulario %}
    {{ parent() }}
    <div class="container editshow">
        <div class="row well">
            <div class="col-xs-4>
                <div class="page-header">
                    <h2>Actualizando oferta</h2>
                </div>
                
                <form action={{ path('trabajos_update', { 'token': entity.token }) }} method="post" {{ form_enctype(edit_form) }}>
                    <div class="form-group">
                        {{ form_label(edit_form.categoria)}}
                        {{ form_widget(edit_form.categoria, {'attr' : {'class' : 'form-control', 'placeholder' : 'Categoria'}}) }}
                        <span class="text-danger">{{ form_errors(edit_form.categoria)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(edit_form.tipo)}}
                        {{ form_widget(edit_form.tipo, {'attr' : {'class' : 'form-control'}}) }}
                        <span class="text-danger">{{ form_errors(edit_form.tipo)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(edit_form.compania)}}
                        {{ form_widget(edit_form.compania, {'attr' : {'class' : 'form-control', 'placeholder' : 'Empresa'}}) }}
                        <span class="text-danger">{{ form_errors(edit_form.compania)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(edit_form.file)}}
                        {{ form_widget(edit_form.file, {'attr' : {'class' : 'form-control'}}) }}
                        <span class="text-danger">{{ form_errors(edit_form.file)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(edit_form.url)}}
                        {{ form_widget(edit_form.url, {'attr' : {'class' : 'form-control', 'placeholder' : 'Website empresa'}}) }}
                        <span class="text-danger">{{ form_errors(edit_form.url)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(edit_form.posicion)}}
                        {{ form_widget(edit_form.posicion, {'attr' : {'class' : 'form-control', 'placeholder' : 'Puesto a desemplear'}}) }}
                        <span class="text-danger">{{ form_errors(edit_form.posicion)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(edit_form.localidad)}}
                        {{ form_widget(edit_form.localidad, {'attr' : {'class' : 'form-control', 'placeholder' : 'Localidad oferta'}}) }}
                        <span class="text-danger">{{ form_errors(edit_form.localidad)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(edit_form.descripcion)}}
                        {{ form_widget(edit_form.descripcion, {'attr' : {'class' : 'form-control', 'placeholder' : 'Descripción oferta'}}) }}
                        <span class="text-danger">{{ form_errors(edit_form.descripcion)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(edit_form.how_to_apply)}}
                        {{ form_widget(edit_form.how_to_apply, {'attr' : {'class' : 'form-control', 'placeholder' : 'Como apuntarse'}}) }}
                        <span class="text-danger">{{ form_errors(edit_form.how_to_apply)}}</span>
                    </div>
                    <div class="checkbox">
                        <label>
                            {{ form_widget(edit_form.publico)}}
                        </label>
                        {{ form_label(edit_form.publico)}}
                        <span class="text-danger">{{ form_errors(edit_form.publico)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(edit_form.email)}}
                        {{ form_widget(edit_form.email, {'attr' : {'class' : 'form-control', 'placeholder' : 'Email de contacto'}}) }}
                        <span class="text-danger">{{ form_errors(edit_form.email)}}</span>
                    </div>
                    
                    <p>
                        <a href="{{ path('trabajos') }}" class="btn btn-info" role="button">Volver a la lista</a>
                        <a href="{{ url('trabajos_preview', {'token': entity.token, 'compania': entity.companiaSlug, 'localidad': entity.localidadSlug, 'posicion': entity.posicionSlug }) }}" class="btn btn-info" role="button">Vista previa</a>
                        <button type="submit" class="btn btn-info">Actualizar</button>
                    </p>
                        
                {{ form_rest(edit_form)}}
            </div>
        </div>
    </div>
{% endblock %}

src/Dsg/agenciaBundle/Resources/views/Trabajos/index.html.twig
{% extends 'DsgagenciaBundle::layout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <!-- CSS carousel-->
    <link rel="stylesheet" href="{{ asset('public/css/carousel.css') }}" type="text/css" media="all" />
    <link rel="stylesheet" href="{{ asset('public/css/trabajos.css') }}" type="text/css" media="all" />
{% endblock %}
{% block body %}
    {{ parent() }}
    {{ include('DsgagenciaBundle::/Trabajos/carousel.html.twig') }}
{% endblock %}
   {% block content %}
    <div id="trabajos">    
        <!-- Three columns of text below the carousel -->
        {% for categoria in categorias %}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h2 class="panel-title"><a href={{ path('dsgagencia_categoria', { 'slug': categoria.slug }) }}>{{ categoria.nombre }}</a></h2>
                </div>
                
                <!--Incluimos la plantilla de listar trabajos-->
                {{ include ('DsgagenciaBundle:Trabajos:listar.html.twig', {'trabajos': categoria.trabajosactivos}) }}
                
                {% if categoria.masTrabajos %}
                    <div class="mas center-block">
                    <a class="btn btn-primary" href="{{ path('dsgagencia_categoria', { 'slug': categoria.slug}) }}" role="button">{{categoria.masTrabajos }} ofertas más...</a>
                    </div>
                {% endif %}
                <div class="clearfix"></div>
                <br/>
            </div>
        {% endfor %}
        </div>
    {% endblock %}

src/Dsg/agenciaBundle/Resources/views/Trabajos/listar.html.twig
<div class="row">
  {% for entity in trabajos %}
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
            <img src="{{ asset('public/upload/') }}{{ entity.logo }}" alt="{{ entity.compania }} logo" style="max-height: 58px; width: auto;"/>
          <div class="caption">
            <h3>{{ entity.compania}}</h3>
            <p>{{ entity.posicion }} - {{ entity.localidad }}</p>
            <p><a href="{{ path('trabajos_show', { 'id': entity.id,'compania': entity.companiaSlug,'localidad': entity.localidadSlug,'posicion': entity.posicionSlug}) }}" class="btn btn-primary" role="button">Leer más</a> </p>
          </div>
        </div>
      </div>
    {% endfor %}
</div>

src/Dsg/agenciaBundle/Resources/views/Trabajos/new.html.twig
{% extends 'DsgagenciaBundle::layout.html.twig' %}

{% form_theme form _self %}
 
{% block form_errors %}
{% spaceless %}
    {% if errors|length > 0 %}
        <ul class="error_list">
            {% for error in errors %}
                <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endspaceless %}
{% endblock form_errors %}


{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('public/csspaginas/show.css') }}" type="text/css" media="all" />
{% endblock %}

{% block formulario %}
    <div class="container">
        <div class="row well">
            <div class="col-xs-12 col-md-6">
                <div class="page-header">
                    <h2>Insertar oferta nueva</h2>
                </div>
                
                <form action={{ path('trabajos_create') }} method="post" {{ form_enctype(form) }}>
                    <div class="form-group">
                        {{ form_label(form.categoria)}}
                        {{ form_widget(form.categoria, {'attr' : {'class' : 'form-control', 'placeholder' : 'Categoria'}}) }}
                        <span class="text-danger">{{ form_errors(form.categoria)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.tipo)}}
                        {{ form_widget(form.tipo, {'attr' : {'class' : 'form-control'}}) }}
                        <span class="text-danger">{{ form_errors(form.tipo)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.compania)}}
                        {{ form_widget(form.compania, {'attr' : {'class' : 'form-control', 'placeholder' : 'Empresa'}}) }}
                        <span class="text-danger">{{ form_errors(form.compania)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.file)}}
                        {{ form_widget(form.file, {'attr' : {'class' : 'form-control'}}) }}
                        <span class="text-danger">{{ form_errors(form.file)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.url)}}
                        {{ form_widget(form.url, {'attr' : {'class' : 'form-control', 'placeholder' : 'Website empresa'}}) }}
                        <span class="text-danger">{{ form_errors(form.url)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.posicion)}}
                        {{ form_widget(form.posicion, {'attr' : {'class' : 'form-control', 'placeholder' : 'Puesto a desemplear'}}) }}
                        <span class="text-danger">{{ form_errors(form.posicion)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.localidad)}}
                        {{ form_widget(form.localidad, {'attr' : {'class' : 'form-control', 'placeholder' : 'Localidad oferta'}}) }}
                        <span class="text-danger">{{ form_errors(form.localidad)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.descripcion)}}
                        {{ form_widget(form.descripcion, {'attr' : {'class' : 'form-control', 'placeholder' : 'Descripción oferta'}}) }}
                        <span class="text-danger">{{ form_errors(form.descripcion)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.how_to_apply)}}
                        {{ form_widget(form.how_to_apply, {'attr' : {'class' : 'form-control', 'placeholder' : 'Como apuntarse'}}) }}
                        <span class="text-danger">{{ form_errors(form.how_to_apply)}}</span>
                    </div>
                    <div class="checkbox">
                        <label>
                            {{ form_widget(form.publico)}}
                        </label>
                        {{ form_label(form.publico)}}
                        <span class="text-danger">{{ form_errors(form.publico)}}</span>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.email)}}
                        {{ form_widget(form.email, {'attr' : {'class' : 'form-control', 'placeholder' : 'Email de contacto'}}) }}
                        <span class="text-danger">{{ form_errors(form.email)}}</span>
                    </div>
                    
                    <p>
                        <button type="submit" class="btn btn-info">Crear</button>
                        <a href="{{ path('trabajos') }}" class="btn btn-info" role="button">Volver a la lista</a>
                    </p>
                        
                {{ form_rest(form)}}
            </div>
        </div>
    </div>
{% endblock %}

src/Dsg/agenciaBundle/Resources/views/Trabajos/show.html.twig
{% extends 'DsgagenciaBundle::layout.html.twig' %}

{% block stylesheets %}
    <!-- CSS carousel-->
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('public/csspaginas/show.css') }}" type="text/css" media="all" />

{% endblock %}

{% block content %}
    
    <div class="container trabajoshow">
        <div class="col-md-9 col-xs-offset-1">
            
            {% if app.request.get('token') %}
                {{ include('DsgagenciaBundle::Trabajos/admin.html.twig', { 'trabajos': entity }) }}
            {% endif %}
            
            {% for flashMessage in app.session.flashbag.get('Mensaje') %}
                <div class="alert alert-sucess" role="alert">
                    <div class="container">
                        {{ flashMessage }}
                    </div>
                </div>
            {% endfor %}
            <h2>Oferta de Empleo - {{ entity.compania }}</h2>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <!-- Podemos utilizar la clase "panel-title" para dar estilo de título
                    al encabezado del panel -->
                    <h1 class="panel-title">{{ entity.compania }}</h1>
                    </div>
                    <div class="panel-body">
                        {% if entity.logo %}
                        <div class="logo">
                            <a href="{{ entity.url }}">
                                <img src="{{ asset('public/upload/') }}{{ entity.logo }}"
                                     alt="{{ entity.compania }} logo" />
                            </a>
                        </div>
                        <h3>
                            {{ entity.posicion }}
                            <small> - {{ entity.tipo }}</small>
                        </h3>
                        <h3>
                            {{ entity.localidad }}
                        </h3>
                    {% endif %}
                        {{ entity.descripcion|nl2br }}
                        
                         <h4>How to apply?</h4>
            
                        <p class="how_to_apply">{{ entity.howtoapply }}</p>
                    </div>
                    
                    <!-- Siempre podemos agregar y personalizar otros elementos dentro de un
                    panel, con estilos compatibles de manera predeterminada. Aquí agregamos
                    un pie para el panel (alineado a la derecha) con un botón predeterminado -->
                    <div class="panel-footer text-right">
                        <small>Creado el {{ entity.creado|date('d/m/Y') }}</small>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}